services:
  qpanel:
    # build: .
    image: ghcr.io/liamniou/qpanel:sha-5f1afe6
    container_name: qpanel
    ports:
      - "${FLASK_PORT:-5001}:5001"
    volumes:
      - ./data:/app/data
      # - /media/downloads/:/downloads:rw
    restart: unless-stopped
